<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>UnifiDownloader.Infrastructure</AssemblyName>
    <RootNamespace>UnifiDownloader.Infrastructure</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../UnifiDownloader.Core/UnifiDownloader.Core.csproj" />
  </ItemGroup>
</Project>
